# -*- coding: utf-8 -*-
# Copyright: (c) 2016, Chamchenko
# GNU General Public License v2.0+ (see LICENSE.txt or https://www.gnu.org/licenses/gpl-2.0.txt)
# This file is part of plugin.video.shahid

GENRES_TVSHOWS = [
                        {'id': '', 'title_ar': 'الكل', 'title_en': 'All'},
                        {'id': 7876, 'title_ar': 'دراما', 'title_en': 'Drama'},
                        {'id': 7871, 'title_ar': 'رومانسي', 'title_en': 'Romantic'},
                        {'id': 10077, 'title_ar': 'قريباً', 'title_en': 'Soon'},
                        {'id': 7858, 'title_ar': 'كوميديا', 'title_en': 'Comedy'},
                        {'id': 9651, 'title_ar': 'غموض', 'title_en': 'Mystery'},
                        {'id': 8153, 'title_ar': 'بوليوود', 'title_en': 'Bollywood'},
                        {'id': 10354, 'title_ar': 'رمضان 2021', 'title_en': 'Ramadan 2021'},
                        {'id': 9649, 'title_ar': 'رسوم متحركة', 'title_en': 'Cartoons'},
                        {'id': 7863, 'title_ar': 'اجتماعي', 'title_en': 'Social'},
                        {'id': 9657, 'title_ar': 'تشويق', 'title_en': 'Thriler'},
                        {'id': 10133, 'title_ar': 'إثارة', 'title_en': 'Excitement'},
                        {'id': 7936, 'title_ar': 'إثارة وتشويق', 'title_en': 'Suspense'},
                        {'id': 7935, 'title_ar': 'أكشن', 'title_en': 'Action'},
                        {'id': 9859, 'title_ar': 'أطفال', 'title_en': 'Kids'},
                        {'id': 7877, 'title_ar': 'كارتون', 'title_en': 'Cartoon'},
                        {'id': 7873, 'title_ar': 'تاريخي', 'title_en': 'Historical'},
                        {'id': 7860, 'title_ar': 'رياضة', 'title_en': 'Sport'},
                        {'id': 10125, 'title_ar': 'أنيمي', 'title_en': 'Anime'},
                        {'id': 9823, 'title_ar': 'خيال', 'title_en': 'Fiction'},
                        {'id': 9830, 'title_ar': 'عائلي', 'title_en': 'Family'},
                        {'id': 9654, 'title_ar': 'مغامرة', 'title_en': 'Adventure'},
                        {'id': 7939, 'title_ar': 'جريمة', 'title_en': 'Crime'},
                        {'id': 9829, 'title_ar': 'تعليمي', 'title_en': 'Educational'},
                        {'id': 7870, 'title_ar': 'موسيقي', 'title_en': 'Musical'},
                        {'id': 9655, 'title_ar': 'سيرة ذاتية', 'title_en': 'Biography'},
                        {'id': 7882, 'title_ar': 'وثائقي', 'title_en': 'Documentary'},
                        {'id': 9652, 'title_ar': 'خيال علمي', 'title_en': 'Sci-Fi'},
                        {'id': 7864, 'title_ar': 'تلفزيون الواقع', 'title_en': 'Reality TV'},
                        {'id': 10091, 'title_ar': 'مترجم', 'title_en': 'Subtitled'},
                        {'id': 7872, 'title_ar': 'رعب', 'title_en': 'Horror'},
                        {'id': 7868, 'title_ar': 'سياسي', 'title_en': 'Political'},
                        {'id': 9799, 'title_ar': 'واقعي', 'title_en': 'Realistic'},
                        {'id': 7938, 'title_ar': 'مسرحية', 'title_en': 'Play'},
                        {'id': 9828, 'title_ar': 'ترفيهي', 'title_en': 'Entertainment'},
                        {'id': 10092, 'title_ar': 'مدبلج', 'title_en': 'Dubbed'},
                        {'id': 8150, 'title_ar': 'مقابلات', 'title_en': 'Interviews'},
                        {'id': 9807, 'title_ar': 'حواري', 'title_en': 'Talk Show'},
                        {'id': 9801, 'title_ar': 'تحقيقات', 'title_en': 'Investigations'},
                        {'id': 9656, 'title_ar': 'نفسي', 'title_en': 'Psychological'},
                        {'id': 9803, 'title_ar': 'تكنولوجيا', 'title_en': 'Technology'},
                        {'id': 7869, 'title_ar': 'ديني', 'title_en': 'Religious'},
                        {'id': 9826, 'title_ar': 'ما قبل المدرسة', 'title_en': 'Pre School'},
                        {'id': 7867, 'title_ar': 'لايف ستايل', 'title_en': 'LifeStyle'},
                        {'id': 9796, 'title_ar': 'طبخ', 'title_en': 'Cooking'},
                        {'id': 9650, 'title_ar': 'طبيعة', 'title_en': 'Nature'},
                        {'id': 9949, 'title_ar': 'حفلات', 'title_en': 'Concerts'},
                        {'id': 7866, 'title_ar': 'سياحة', 'title_en': 'Tourism'},
                        {'id': 9706, 'title_ar': 'بيئة شامية', 'title_en': 'Levantine Series'},
                        {'id': 7883, 'title_ar': 'برنامج', 'title_en': 'Program'},
                        {'id': 10105, 'title_ar': 'أصدقاء', 'title_en': 'Friends'}
                 ]



DIALECTS_TVSHOWS = [
                        {'id': '', 'title_ar': 'الكل', 'title_en': 'All'},
                        {'id': 7915, 'title_ar': 'مصري', 'title_en': 'Egyptian'},
                        {'id': 7911, 'title_ar': 'خليجي', 'title_en': 'Gulf'},
                        {'id': 7908, 'title_ar': 'عربي', 'title_en': 'Arabic'},
                        {'id': 7929, 'title_ar': 'باكستاني مدبلج', 'title_en': 'Dubbed Pakistani'},
                        {'id': 8147, 'title_ar': 'سعودي', 'title_en': 'Saudi'},
                        {'id': 9858, 'title_ar': 'أطفال عربي', 'title_en': 'Kids Arabic'},
                        {'id': 7909, 'title_ar': 'عراقي', 'title_en': 'Iraqi'},
                        {'id': 7918, 'title_ar': 'سوري', 'title_en': 'Syrian'},
                        {'id': 8149, 'title_ar': 'مغربي', 'title_en': 'Moroccan'},
                        {'id': 7919, 'title_ar': 'كوري مدبلج', 'title_en': 'Dubbed Korean'},
                        {'id': 9819, 'title_ar': 'الأجنبية', 'title_en': 'Foreign'},
                        {'id': 7921, 'title_ar': 'الإنجليزية', 'title_en': 'English'},
                        {'id': 9941, 'title_ar': 'أطفال مدبلج', 'title_en': 'Kids Dubbed'},
                        {'id': 7916, 'title_ar': 'لبناني', 'title_en': 'Lebanese'},
                        {'id': 9798, 'title_ar': 'الفرنسية', 'title_en': 'French'},
                        {'id': 8180, 'title_ar': 'كوري', 'title_en': 'Korean'},
                        {'id': 9931, 'title_ar': 'أطفال انجليزي', 'title_en': 'Kids English'},
                        {'id': 7912, 'title_ar': 'هندي مدبلج', 'title_en': 'Dubbed Indian'},
                        {'id': 7920, 'title_ar': 'لاتيني مدبلج', 'title_en': 'Dubbed Latin'},
                        {'id': 7917, 'title_ar': 'أردني', 'title_en': 'Jordanian'},
                        {'id': 10100, 'title_ar': 'أجنبي مدبلج', 'title_en': 'Foreign dubbed'},
                        {'id': 7914, 'title_ar': 'تركي مدبلج', 'title_en': 'Dubbed Turkish'},
                        {'id': 8151, 'title_ar': 'هندي', 'title_en': 'Indian'},
                        {'id': 9783, 'title_ar': 'لاتيني مترجم', 'title_en': 'Latin Translated'}
                   ]


GENRES_PROGRAMS = [
                        {'id': '', 'title_ar': 'الكل', 'title_en': 'All'},
                        {'id': 7860, 'title_ar': 'رياضة', 'title_en': 'Sport'},
                        {'id': 10077, 'title_ar': 'قريباً', 'title_en': 'Soon'},
                        {'id': 7870, 'title_ar': 'موسيقي', 'title_en': 'Musical'},
                        {'id': 9828, 'title_ar': 'ترفيهي', 'title_en': 'Entertainment'},
                        {'id': 10354, 'title_ar': 'رمضان 2021', 'title_en': 'Ramadan 2021'},
                        {'id': 9796, 'title_ar': 'طبخ', 'title_en': 'Cooking'},
                        {'id': 9830, 'title_ar': 'عائلي', 'title_en': 'Family'},
                        {'id': 7863, 'title_ar': 'اجتماعي', 'title_en': 'Social'},
                        {'id': 7883, 'title_ar': 'برنامج', 'title_en': 'Program'},
                        {'id': 9655, 'title_ar': 'سيرة ذاتية', 'title_en': 'Biography'},
                        {'id': 7867, 'title_ar': 'لايف ستايل', 'title_en': 'LifeStyle'},
                        {'id': 7882, 'title_ar': 'وثائقي', 'title_en': 'Documentary'},
                        {'id': 7858, 'title_ar': 'كوميديا', 'title_en': 'Comedy'},
                        {'id': 7936, 'title_ar': 'إثارة وتشويق', 'title_en': 'Suspense'},
                        {'id': 7864, 'title_ar': 'تلفزيون الواقع', 'title_en': 'Reality TV'},
                        {'id': 9649, 'title_ar': 'رسوم متحركة', 'title_en': 'Cartoons'},
                        {'id': 9859, 'title_ar': 'أطفال', 'title_en': 'Kids'},
                        {'id': 7869, 'title_ar': 'ديني', 'title_en': 'Religious'},
                        {'id': 10133, 'title_ar': 'إثارة', 'title_en': 'Excitement'},
                        {'id': 9654, 'title_ar': 'مغامرة', 'title_en': 'Adventure'},
                        {'id': 9807, 'title_ar': 'حواري', 'title_en': 'Talk Show'},
                        {'id': 7873, 'title_ar': 'تاريخي', 'title_en': 'Historical'},
                        {'id': 9949, 'title_ar': 'حفلات', 'title_en': 'Concerts'},
                        {'id': 8150, 'title_ar': 'مقابلات', 'title_en': 'Interviews'},
                        {'id': 7868, 'title_ar': 'سياسي', 'title_en': 'Political'},
                        {'id': 10091, 'title_ar': 'مترجم', 'title_en': 'Subtitled'},
                        {'id': 7876, 'title_ar': 'دراما', 'title_en': 'Drama'},
                        {'id': 9650, 'title_ar': 'طبيعة', 'title_en': 'Nature'},
                        {'id': 9803, 'title_ar': 'تكنولوجيا', 'title_en': 'Technology'},
                        {'id': 7938, 'title_ar': 'مسرحية', 'title_en': 'Play'},
                        {'id': 9799, 'title_ar': 'واقعي', 'title_en': 'Realistic'},
                        {'id': 9829, 'title_ar': 'تعليمي', 'title_en': 'Educational'},
                        {'id': 8153, 'title_ar': 'بوليوود', 'title_en': 'Bollywood'},
                        {'id': 9657, 'title_ar': 'تشويق', 'title_en': 'Thriler'},
                        {'id': 7877, 'title_ar': 'كارتون', 'title_en': 'Cartoon'},
                        {'id': 7866, 'title_ar': 'سياحة', 'title_en': 'Tourism'},
                        {'id': 7935, 'title_ar': 'أكشن', 'title_en': 'Action'},
                        {'id': 7858, 'title_ar': 'كوميديا', 'title_en': 'كوميديا'},
                        {'id': 9823, 'title_ar': 'خيال', 'title_en': 'Fiction'}
                  ]

DIALECTS_PROGRAMS = [
                        {'id': '', 'title_ar': 'الكل', 'title_en': 'All'},
                        {'id': 7921, 'title_ar': 'الإنجليزية', 'title_en': 'English'},
                        {'id': 7908, 'title_ar': 'عربي', 'title_en': 'Arabic'},
                        {'id': 7915, 'title_ar': 'مصري', 'title_en': 'Egyptian'},
                        {'id': 8149, 'title_ar': 'مغربي', 'title_en': 'Moroccan'},
                        {'id': 8147, 'title_ar': 'سعودي', 'title_en': 'Saudi'},
                        {'id': 9858, 'title_ar': 'أطفال عربي', 'title_en': 'Kids Arabic'},
                        {'id': 7909, 'title_ar': 'عراقي', 'title_en': 'Iraqi'},
                        {'id': 7911, 'title_ar': 'خليجي', 'title_en': 'Gulf'},
                        {'id': 7916, 'title_ar': 'لبناني', 'title_en': 'Lebanese'},
                        {'id': 7914, 'title_ar': 'تركي مدبلج', 'title_en': 'Dubbed Turkish'},
                        {'id': 8151, 'title_ar': 'هندي', 'title_en': 'Indian'}
                    ]



DIALECTS_MOVIES = [
                    {'id': '', 'title_ar': 'الكل', 'title_en': 'All'},
                    {'id': 7921, 'title_ar': 'الإنجليزية', 'title_en': 'English'},
                    {'id': 7915, 'title_ar': 'مصري', 'title_en': 'Egyptian'},
                    {'id': 7911, 'title_ar': 'خليجي', 'title_en': 'Gulf'},
                    {'id': 7908, 'title_ar': 'عربي', 'title_en': 'Arabic'},
                    {'id': 8147, 'title_ar': 'سعودي', 'title_en': 'Saudi'},
                    {'id': 7916, 'title_ar': 'لبناني', 'title_en': 'Lebanese'}
                  ]
GENRES_MOVIES = [
                    {'id': '', 'title_ar': 'الكل', 'title_en': 'All'},
                    {'id': 7935, 'title_ar': 'أكشن', 'title_en': 'Action'},
                    {'id': 10077, 'title_ar': 'قريباً', 'title_en': 'Soon'},
                    {'id': 9830, 'title_ar': 'عائلي', 'title_en': 'Family'},
                    {'id': 9654, 'title_ar': 'مغامرة', 'title_en': 'Adventure'},
                    {'id': 9655, 'title_ar': 'سيرة ذاتية', 'title_en': 'Biography'},
                    {'id': 7858, 'title_ar': 'كوميديا', 'title_en': 'Comedy'},
                    {'id': 9649, 'title_ar': 'رسوم متحركة', 'title_en': 'Cartoons'},
                    {'id': 7938, 'title_ar': 'مسرحية', 'title_en': 'Play'},
                    {'id': 7882, 'title_ar': 'وثائقي', 'title_en': 'Documentary'},
                    {'id': 9828, 'title_ar': 'ترفيهي', 'title_en': 'Entertainment'},
                    {'id': 10354, 'title_ar': 'رمضان 2021', 'title_en': 'Ramadan 2021'},
                    {'id': 9652, 'title_ar': 'خيال علمي', 'title_en': 'Sci-Fi'},
                    {'id': 7936, 'title_ar': 'إثارة وتشويق', 'title_en': 'Suspense'},
                    {'id': 7872, 'title_ar': 'رعب', 'title_en': 'Horror'},
                    {'id': 9651, 'title_ar': 'غموض', 'title_en': 'Mystery'},
                    {'id': 10194, 'title_ar': 'طبي', 'title_en': 'Medical'},
                    {'id': 7873, 'title_ar': 'تاريخي', 'title_en': 'Historical'},
                    {'id': 7876, 'title_ar': 'دراما', 'title_en': 'Drama'},
                    {'id': 7860, 'title_ar': 'رياضة', 'title_en': 'Sport'},
                    {'id': 7871, 'title_ar': 'رومانسي', 'title_en': 'Romantic'},
                    {'id': 10133, 'title_ar': 'إثارة', 'title_en': 'Excitement'},
                    {'id': 7939, 'title_ar': 'جريمة', 'title_en': 'Crime'}
                ]

